version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
